# Generated by Django 3.2.25 on 2024-11-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0002_alter_journal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
