# Generated by Django 3.2.25 on 2024-11-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0004_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='location',
        ),
        migrations.AddField(
            model_name='journal',
            name='location',
            field=models.ManyToManyField(to='Journal.Locations'),
        ),
    ]
