# Generated by Django 3.2.25 on 2024-11-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0005_auto_20241113_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name_plural': 'Locations'},
        ),
    ]
