# Generated by Django 4.2.18 on 2025-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('technology_logo', models.ImageField(upload_to='Projects/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrption', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Projects/images/')),
                ('Technologies', models.ManyToManyField(to='Projects.technologies')),
            ],
        ),
    ]
