# Generated by Django 3.2.25 on 2024-11-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoGallery', '0003_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='images',
            name='image_file',
            field=models.ImageField(upload_to='PhotoGallery/images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='tags',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PhotoGallery.tags'),
        ),
    ]
