# Generated by Django 3.2.25 on 2024-11-13 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoGallery', '0005_alter_images_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='tags',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PhotoGallery.tags'),
        ),
    ]
