# Generated by Django 3.2.25 on 2024-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoGallery', '0006_alter_images_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='tags',
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ManyToManyField(to='PhotoGallery.Tags'),
        ),
    ]
